### ISSUE TITLE
Problem with launching epyseg today

### ISSUE THREAD

**Issue by leovalon** [baigouy/EPySeg#10]
First of all, a big thanks for epyseg, it works very very well in our hands since 2 years, 

However, I wanted to install it again today on a new computer, via anaconda prompt, trying from python 3.7 to 3.9 environnements, and I don't manange to make it run, 
I especially have the following error running it on Python 3.9 (see below), do you have any idea why !?
All the best, 
Léo Valon, CNRS researcher in R Levayer Lab, institut Pasteur

(epyseg_39) C:\Users\levalon>python -m epyseg
Traceback (most recent call last):
  File "C:\Users\levalon\AppData\Local\anaconda3\envs\epyseg_39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\levalon\AppData\Local\anaconda3\envs\epyseg_39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\levalon\AppData\Local\anaconda3\envs\epyseg_39\lib\site-packages\epyseg\__main__.py", line 3, in <module>
    from epyseg.epygui import EPySeg
  File "C:\Users\levalon\AppData\Local\anaconda3\envs\epyseg_39\lib\site-packages\epyseg\epygui.py", line 14, in <module>
    from epyseg.gui.mini.miniGUI_selection_dialog import minisel
  File "C:\Users\levalon\AppData\Local\anaconda3\envs\epyseg_39\lib\site-packages\epyseg\gui\mini\miniGUI_selection_dialog.py", line 17, in <module>
    from epyseg.gui.preview import crop_or_preview
  File "C:\Users\levalon\AppData\Local\anaconda3\envs\epyseg_39\lib\site-packages\epyseg\gui\preview.py", line 7, in <module>
    from epyseg.draw.widgets.paint import Createpaintwidget
  File "C:\Users\levalon\AppData\Local\anaconda3\envs\epyseg_39\lib\site-packages\epyseg\draw\widgets\paint.py", line 14, in <module>
    from epyseg.draw.widgets.vectorial import VectorialDrawPane
  File "C:\Users\levalon\AppData\Local\anaconda3\envs\epyseg_39\lib\site-packages\epyseg\draw\widgets\vectorial.py", line 20, in <module>
    from epyseg.draw.shapes.image2d import Image2D
  File "C:\Users\levalon\AppData\Local\anaconda3\envs\epyseg_39\lib\site-packages\epyseg\draw\shapes\image2d.py", line 33, in <module>
    from epyseg.matplolib.tools import get_fig_rect
ModuleNotFoundError: No module named 'epyseg.matplolib'

**Comment by leovalon** [comment]
ChatGPT guessed that it is due to a "epyseg.matplolib" being written that way instead of "epyseg.matplotlib" but it doesn't seem to be the case(tested by modifying the import line in image2d.py), isn't it?

**Comment by baigouy** [comment]
Thanks for the bug report, this should be fixed now with version 1.52 (I had forgotten to upload a folder). Ideally, if possible use python 3.10.12 as this is my current development version.

**Comment by leovalon** [comment]
Great, I'll do it !
Have a nice day
And I'll definitely try to work with python 3.10 

Thanks again !

[EDIT] it works
